#!/usr/bin/env python3

from influxdb import InfluxDBClient
from flask import Flask, request
import logging
import datetime

logging.basicConfig(level=logging.INFO)

api = Flask(__name__)

@api.route('/api/v1/metric', methods=['POST'])
def create():
    incoming_data = request.get_json()
    presence = incoming_data['presence']
    logging.info(presence)

    payload = [
        {
            "measurement": "pet_feeder",
            "tags": {
                "name": "miau"
            },
            "time": datetime.datetime.utcnow().isoformat(),
            "fields": {
                "presence": int(presence)
            }
        }
    ]

    influx_client = InfluxDBClient('influxdb', 8086, database='pet_feeder')
    influx_client.write_points(payload)

    return 'Metric created', 201

if __name__ == '__main__':
    api.run(debug=True, host='0.0.0.0', port=3000)
