#!/usr/bin/env python3

from flask import Flask, request
import logging
import time

api = Flask(__name__)

@api.route('/', methods=['GET'])
def index():
    return 'API is up!'

@api.route('/api/v1/metric', methods=['POST'])
def create():
    data = request.get_json()
    timestamp = time.strftime("%x %X", time.gmtime())

    logging.warning("%s %s" % (data['presence'], timestamp))

    return 'Metric created', 201

if __name__ == '__main__':
    api.run(debug=True, host='0.0.0.0', port=3000)
